# Generated by Django 3.2 on 2022-02-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_patient',
            fields=[
                ('idnational', models.IntegerField(primary_key=True, serialize=False)),
                ('file_number', models.CharField(max_length=30, null=True, verbose_name='File Number')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('date', models.DateField(verbose_name='Today Date')),
                ('age', models.CharField(blank=True, max_length=20, null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('adderss', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('mobile_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('diagnosis', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Diagnosis')),
                ('wt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Wt')),
                ('temp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temp')),
                ('treatment', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Treatment')),
                ('next_visit_date', models.DateField(verbose_name='Next Visit Date')),
                ('note', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Dr. Notes')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doctor`s name')),
                ('specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Specialty')),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Mobile Number')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=30, null=True, verbose_name='File Number')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('date', models.DateField(verbose_name='Today Date')),
                ('age', models.CharField(blank=True, max_length=20, null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('adderss', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('mobile_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('wt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Wt')),
                ('temp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temp')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Rosheta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Diagnosis')),
                ('treatment', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Treatment')),
                ('note', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Dr. Notes')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctor', verbose_name='Doctor`s Rosheta')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='Patient Rosheta')),
            ],
            options={
                'verbose_name': 'Roshita',
                'verbose_name_plural': 'Roshita',
            },
        ),
        migrations.CreateModel(
            name='Cashf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Detection Cost')),
                ('date', models.DateField(verbose_name='date Cashf')),
                ('next_visit_date', models.DateField(verbose_name='Next Visit Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctor', verbose_name='Doctor Cashf')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='Patient Cashf')),
            ],
            options={
                'verbose_name': 'Cashf',
                'verbose_name_plural': 'Cashf',
            },
        ),
    ]
