# Generated by Django 3.2 on 2022-03-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20220308_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnational', models.IntegerField()),
                ('file_number', models.CharField(max_length=30, null=True, verbose_name='File Number')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('date', models.DateField(verbose_name='Today Date')),
                ('age', models.CharField(blank=True, max_length=20, null=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('adderss', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('mobile_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('diagnosis', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Diagnosis')),
                ('wt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Wt')),
                ('temp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temp')),
                ('treatment', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Treatment')),
                ('next_visit_date', models.DateField(blank=True, null=True, verbose_name='Next Visit Date')),
                ('note', models.TextField(blank=True, max_length=1200, null=True, verbose_name='Dr. Notes')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registration',
            },
        ),
        migrations.DeleteModel(
            name='Reg_patient',
        ),
        migrations.RemoveField(
            model_name='cashf',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='rosheta',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
