# Generated by Django 3.2 on 2022-03-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_add_patient_idnational'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patient',
            name='idnational',
            field=models.IntegerField(),
        ),
    ]
