# Generated by Django 3.2 on 2022-03-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_add_patient_idnational'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='add_patient',
            name='idnational',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
